name: Build

on:
  push:
    tags:
      - '*'
      
jobs:
  # rustfmt:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: rustup component add rustfmt
  #     - run: cargo fmt -- --check
  
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: milcup
            asset_name: milcup-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: milcup.exe
            asset_name: milcup-windows-amd64.exe
          - os: macOS-latest
            target: x86_64-apple-darwin
            binary: milcup
            asset_name: milcup-macos-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Cache Rust dependencies
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          components: rustfmt, clippy
          
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y  libudev-dev  libdbus-1-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=${{ matrix.target }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.binary }}
          tag: ${{ github.ref }}
          asset_name: ${{ matrix.asset_name }}
          overwrite: true
          body: "Milcup release"

